### ISSUE TITLE
2个疑问？

### ISSUE THREAD

**Issue by frankFree** [jasondu/wxa-plugin-canvas#1]
1、首先这个插件现在审核通过没有
2、支持自定义参数不？获取小程序二维码是不是需要后台

**Comment by jasondu** [comment]
1. 这个插件是没有审核通过的
2. 现在的二维码是写死的，不是通过服务器获取的，这个插件只是起到帮忙绘制海报的功能

**Comment by youngchen1987** [comment]
这么久了还没有通过？

**Comment by jasondu** [comment]
现在已经改成组件的形式
