### ISSUE TITLE
[已解决] 在性能较差的手机中出现资源抢用的状态

### ISSUE THREAD

**Issue by sastar** [jasondu/wxa-plugin-canvas#107]
### ~~bug位置: 出现延迟60s的位置在_downloadImageAndInfo()函数中,在执行第三次this._getImageInfo(imgPath, index)时,和第四次执行this.toRpx()出现资源争抢的情况,造成有大概60s的延迟,建议修复,~~
~~不确定位置~~

**Comment by sastar** [comment]
建议第二个then执行的代码块加个延迟,就可以解决这个问题

**Comment by sastar** [comment]
我发现加个延迟并不能解决...,没办法保证getImageinfo先执行,请作者解决.......

**Comment by jasondu** [comment]
小程序getImageinfo 这个api不能立即执行，解决的办法只能将生成图片的动作后置

**Comment by sastar** [comment]
在我这边测试的时候,getImageInfo前两次是正常返回的,在第三次的时候,迟迟不返回,需要等60秒才可以返回,但是在第二次生成海报的时候,就正常了

**Comment by sastar** [comment]
> 小程序getImageinfo 这个api不能立即执行，解决的办法只能将生成图片的动作后置

请问生成图片的动作不是已经是后置的吗,需要等待获取到所有的图片的信息之后才会执行生成海报的动作,那么生成海报的动作便不会影响到前面的getImageInfo的执行的吧

**Comment by jasondu** [comment]
加我微信把weizaidu

**Comment by chaossssss** [comment]
是不是有引入了微信头像，安卓4G下载微信用户头像会异常慢，可以把头像保存到自己的服务器，调用自己服务器的图片位置

**Comment by sastar** [comment]
> 是不是有引入了微信头像，安卓4G下载微信用户头像会异常慢，可以把头像保存到自己的服务器，调用自己服务器的图片位置

刚刚实验了一下,确实是如此,是由于微信头像下载缓慢导致的,我做了个缓存解决了
