### ISSUE TITLE
api获取的base64格式的图片不支持吗

### ISSUE THREAD

**Issue by dongyunke** [jasondu/wxa-plugin-canvas#14]
api获取的base64格式的图片不支持吗

**Comment by dongyunke** [comment]
接口获取的小程序码，是base64的数据，什么时候可以支持这个格式呢

**Comment by jasondu** [comment]
会在最近版本加上

**Comment by zhangshichuan** [comment]
已经更新了吗

**Comment by qq1628195737** [comment]
还是不支持哦

**Comment by jasondu** [comment]
这个功能根据小程序当前提供的api无法实现

**Comment by Rockergmail** [comment]
把base64生成图片，放到文件系统，然后用文件系统的url就解决了。
https://www.cnblogs.com/kaiye/p/9909304.html
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/file-system.html
