### ISSUE TITLE
显示有问题

### ISSUE THREAD

**Issue by eminfan** [jasondu/wxa-plugin-canvas#16]
生成海报页面左侧会有遮挡
![screenshot_2018-09-26-10-34-43-153_com tencent mm](https://user-images.githubusercontent.com/16729869/46054042-fe81f980-c177-11e8-89cb-1f36a7171f33.png)

橙色边框右上角错位。
![mmexport1537929278172](https://user-images.githubusercontent.com/16729869/46054044-004bbd00-c178-11e8-8780-c6922c58594f.jpg)

**Comment by jasondu** [comment]
给我看看你的配置

**Comment by jasondu** [comment]
我搞不到这个机型，你可否调试修复一下，再提个pull request
