### ISSUE TITLE
请设置组件的id="poster"!!!

### ISSUE THREAD

**Issue by plamYuan** [jasondu/wxa-plugin-canvas#161]
真机调试时，会报：请设置组件的id="poster"!!!错误，并不会不会执行success 或fail方法，小程序开发工具偶尔会出现这种情况。
我确保已经加了 id=poster

**Comment by jasondu** [comment]
真机不会出现吧？可以打打断点看看

**Comment by plamYuan** [comment]
真机不出现，但是我发吧体验版本后，在手机上可以生成
