### ISSUE TITLE
修改config后再次生成，图片没有刷新

### ISSUE THREAD

**Issue by ty-me** [jasondu/wxa-plugin-canvas#163]
修改了config后，重新生成图片不会刷新，还是老图，今天一上午都在调试这个问题，一直以为是我参数写错了，直到看到这个：
https://github.com/jasondu/wxa-plugin-canvas/blob/master/pages/index/index.js#L291

因此，强烈建议，将Poster.create的参数默认值修改为true，而不是false

**Comment by jasondu** [comment]
好的，谢谢建议
