### ISSUE TITLE
生成海报失败：downloadFile:fail url not in domain list

### ISSUE THREAD

**Issue by wupengxiaobai** [jasondu/wxa-plugin-canvas#169]
""system"":{""locationEnabled"":true,""screenWidth"":412,""screenHeight"":732,""windowHeight"":660,""bluetoothEnabled"":false,""language"":""zh_CN"",""microphoneAuthorized"":true,""version"":""7.0.7"",""cameraAuthorized"":true,""system"":""Android9"",""fontSizeSetting"":16,""locationAuthorized"":true,""pixelRatio"":2.625,""notificationAuthorized"":true,""model"":""ONEPLUS A5000"",""statusBarHeight"":24,""deviceOrientation"":""portrait"",""wifiEnabled"":false,""safeArea"":{""width"":412,""right"":412,""top"":0,""left"":0,""bottom"":732,""height"":732},""brand"":""OnePlus"",""windowWidth"":412,""screenTop"":72,""platform"":""android"",""SDKVersion"":""2.9.1"",""devicePixelRatio"":2.625},

""posterFail"":{""type"":""fail"",""timeStamp"":1666393,""target"":{""id"":""poster"",""dataset"":{}},""currentTarget"":{""id"":""poster"",""dataset"":{}},""mark"":{},""detail"":{""errMsg"":""downloadFile:fail url not in domain list""},""mut"":false}}"

**Comment by plamYuan** [comment]
这个应该好明显吧，你的远程图片的域名是不是没有在微信后台设置安全域名
