### ISSUE TITLE
可以增加用户授权判断

### ISSUE THREAD

**Issue by yeyuying2018** [jasondu/wxa-plugin-canvas#175]
在poster.js里的 onCreate方法里可以增加用户授权判断，如果用户拒绝授权的情况下可以再次调起申请，且增加一个参数判断是否在生成过程中，如果在生成过程中则不再执行onCreate方法：代码如下：
onCreate(reset = false) {
          this.checkSetting();
        },
        // 自定义修改 检查用户是否授权
        checkSetting: function(){
          let that = this;
          //是否授权
          wx.getSetting({
            success: function (res) {
              let writePhotosAlbum = res.authSetting["scope.writePhotosAlbum"];
              if (writePhotosAlbum) {
                //已授权
                that.creatPic();
              } else if (writePhotosAlbum != undefined && writePhotosAlbum != true) {
                //关闭分享弹窗
                that.triggerEvent('close');
                //拒绝授权了
                wx.showModal({
                  title: '',
                  content: '您还未授权保存图片到相册，请确认授权',
                  showCancel: true,
                  cancelText: '取消',
                  confirmText: '确认',
                  success: function (e) {
                    //点了查看规则
                    if (e.confirm) {
                      //针对用户保存图片的时候可能会拒绝授权，再次点击时需要调起授权窗口
                      that.openSetting();
                    } else {
                      //取消
                    }
                  }
                })
              } else {
                that.creatPic();
              }
            }
          })
        },
        // 自定义修改 未授权重新调起授权弹窗
        openSetting: function () {
          let that = this;
          //调起授权弹窗
          wx.openSetting({
            success(res) {
              //同意授权
              if (res.authSetting["scope.writePhotosAlbum"]) {
                that.creatPic();
              }
            }
          });
        },
        //自定义修改 分离出生成图片方法
        creatPic: function () {
          //正在生成
          let that = this;
          if (that.data.isCreating){
            wx.showToast({
              title: '图片正在生成中，请稍后再试',
              icon: 'none'
            })
            return;
          }
          //自定义参数 避免生成过程中重复点击
          that.data.isCreating = 1;
          !that.data.hideLoading && wx.showLoading({ mask: true, title: '正在生成图片...' });
          return that.downloadResource(typeof reset === 'boolean' && reset).then(() => {
            !that.data.hideLoading && wx.hideLoading();
            const poster = that.selectComponent('#poster');
            poster.create(that.data.config);
          })
            .catch((err) => {
              !that.data.hideLoading && wx.hideLoading();

              // 因此自定义修改
              //wx.showToast({ icon: 'none', title: err.errMsg || '生成失败' });
              wx.showToast({ icon: 'none', title: '图片生成失败，请稍后重试' });
              that.data.isCreating = 0;
              that.triggerEvent('fail', err);
            })
        },
        onCreateSuccess(e) {
          const { detail } = e;
          this.data.isCreating = 0;
          this.triggerEvent('success', detail);
        },
        onCreateFail(err) {
          this.data.isCreating = 0;
          this.triggerEvent('fail', err);
        }

**Comment by jasondu** [comment]
谢谢，可以发起一个Pull request
