### ISSUE TITLE
Setting data field "debug" to undefined is invalid.

### ISSUE THREAD

**Issue by 1170197998** [jasondu/wxa-plugin-canvas#19]
Setting data field "debug" to undefined is invalid.

**Comment by LeachZhou** [comment]
这个是什么原因导致的？@jasondu

**Comment by shaobeichen** [comment]
这里这个问题其实是，如果你的posterConfig一开始没有设置debug，在进入页面加载到poster组件的时候会报这个错，给默认的posterConfig设置一个默认的debug: false就行了
