### ISSUE TITLE
生成的图片尺寸不稳定问题

### ISSUE THREAD

**Issue by houyanchao** [jasondu/wxa-plugin-canvas#2]
return {
        width: 500,
        height: 400,
        backgroundColor: '#fff',
        debug: false,
        borderColor: 'blue',
        blocks: [
            {
                width: 485,
                height: 383,
                x: 7,
                y: 8,
                borderWidth: 10,
                borderColor: '#CD5145'
            }
        ],
        images: [
            {
                width: 440,
                height: 225,
                x: 30,
                y: 32,
                url: "http://image.wulion.com/20180825/15351905175135.o6zAJs2kEQGWHOtjeKTN1qHD08cA",
            }
        ],
        texts: [{
                x: 30,
                y: 296,
                baseLine: 'middle',
                text: "奖品：锤子手机",
                width: 414,
                lineNum: 1,
                fontSize: 32,
                color: '#28354c',
        },{
                x: 30,
                y: 342,
                baseLine: 'middle',
                text: "人数满 100 人自动开奖",
                fontSize: 28,
                color: '#8d8d8d',
        }]
    }

**Comment by jasondu** [comment]
重现不出来，请提供重现的条件和机型，系统版本号，微信版本号
