### ISSUE TITLE
downloadFile: fail url not in domain list

### ISSUE THREAD

**Issue by spirodelazz** [jasondu/wxa-plugin-canvas#205]
我在模拟器上是可以生成海报的，但是运行体验版的时候出现“**downloadFile: fail url not in domain list**”。
我已经配置了downloadFile的合法域名。

**Comment by laeo** [comment]
我也遇到了，兄台你解决了吗？

**Comment by laeo** [comment]
额，找到原因了，我这是下载微信头像的域名没加到白名单……

**Comment by spirodelazz** [comment]
> 额，找到原因了，我这是下载微信头像的域名没加到白名单……

我隔了两天又重新运行了一次，啥都没改，然后又可以了。。。。真搞心态。。。。
