### ISSUE TITLE
画布上图片画布不成圆形

### ISSUE THREAD

**Issue by LuckFairy** [jasondu/wxa-plugin-canvas#24]
![image](https://user-images.githubusercontent.com/21116962/46795049-bc61d600-cd7b-11e8-82ef-d2a27f41ad3e.png)
如图，我参数上有配borderRadius,部分参数如下
images: [
        {
          width: 160,
          height: 160,
          x: 296,
          y: 180,
          url: 'https://zy.qutego.com//upload/images/000/000/293/201808/5b861e3aeb9fd.png',
          borderRadius:160,
          borderWidth:6,
          borderColor:'#fff',
          zIndex: 2
        }
]
为何出现上面情况，有什么解决方法

**Comment by yuanmao5200** [comment]
好像设置了背景颜色就会出现这个样子

**Comment by jasondu** [comment]
加一下微信weizaidu

**Comment by 420381218** [comment]
nokia plus 7 画的圆形头像缺了一块（图片1，2）， 小米魅族iPhone上都是正常的（图片3）
![2](https://user-images.githubusercontent.com/13251205/47613834-e849bf00-dad0-11e8-9285-05c0a670fb6e.jpg)

![1](https://user-images.githubusercontent.com/13251205/47613833-e7b12880-dad0-11e8-8be5-0a7cfd258446.jpg)

![3](https://user-images.githubusercontent.com/13251205/47613835-e8e25580-dad0-11e8-80a1-e2c36906cb7a.jpg)

**Comment by 420381218** [comment]
不好意思 刚看到5天前更新了 我更新一下再试试
