### ISSUE TITLE
texts的textAlign设置为center|right的时候显示不正常

### ISSUE THREAD

**Issue by 420381218** [jasondu/wxa-plugin-canvas#25]

**Comment by 420381218** [comment]
![wechatimg443](https://user-images.githubusercontent.com/13251205/46850754-a90c4480-ce27-11e8-8d73-f844a2fc5159.jpeg)

**Comment by 420381218** [comment]
{
                    x: 30,
                    y: 113,
                    baseLine: 'top',
                    text: '发现一个好物，推荐给你呀',
                    fontSize: 38,
                    color: '#080808',
                  textAlign: 'center',
                },
                {
                    x: 92,
                    y: 810,
                    fontSize: 38,
                    baseLine: 'middle',
                    text: '标题标题标',
                    width: 570,
                    lineNum: 1,
                    color: '#8d8d8d',
                    zIndex: 200,
                  textAlign: 'center',
                },

**Comment by jasondu** [comment]
center是表示x,y为对齐的中点，所以修改对齐方式，x,y也要修改
