### ISSUE TITLE
图片比较多的时候，有的图片画不完整，是框架的问题，还是小程序canvas的问题

### ISSUE THREAD

**Issue by aYangLi** [jasondu/wxa-plugin-canvas#28]

**Comment by jasondu** [comment]
请详细描述，最好包括截图

**Comment by aYangLi** [comment]
> 请详细描述，最好包括截图

最后测试发现：是个别图，但是这些个别图没找到规律，在安卓机会出现，ios 不出现。

**Comment by w19871029** [comment]
@aYangLi 是比较大的图吗 我的是png 超过400多KB 就不行了 添加了延迟也不行 画图和生成画好的图 这种异步方式

**Comment by MyCodeMyWorld** [comment]
遇到了同样问题，多图时出现
