### ISSUE TITLE
安卓手机图片显示尺寸有问题

### ISSUE THREAD

**Issue by pijunhuis** [jasondu/wxa-plugin-canvas#29]
![_20181018152432](https://user-images.githubusercontent.com/24618917/47137695-f2f2a000-d2e9-11e8-97ab-e641315cd175.jpg)
![_20181018152437](https://user-images.githubusercontent.com/24618917/47137700-f554fa00-d2e9-11e8-857c-2e96c2b286f4.jpg)
能够正常显示的是iphone手机

**Comment by jasondu** [comment]
看来这个问题还挺多的，我去找一台安卓手机调试一下

**Comment by chaituan** [comment]
@jasondu   我的小米5  也是这样子的， 我在网上找了一个 算法，把你的圆角算法替换掉  就好了。 但是苹果又会出问题 ，好尴尬 ....

**Comment by jasondu** [comment]
这个问题已经解决，是微信arcTo API的bug导致的，改动地方：https://github.com/jasondu/wxa-plugin-canvas/commit/37a685fa5160a791faa9bed90699eb9c33ce14e7
