### ISSUE TITLE
生成画布以后，原页面保留了画布

### ISSUE THREAD

**Issue by ifuweimin** [jasondu/wxa-plugin-canvas#30]
你好，我这边测试点击生成画布成功以后， 默认跳出预览，把预览关闭以后， 原页面会保留画布的图片，覆盖了原页面的dom， 6s， ios12系统，请问是什么问题？

![img_4605](https://user-images.githubusercontent.com/5689131/47213147-c82d4800-d3cc-11e8-8412-bbf04f59d778.PNG)

**Comment by frontbear** [comment]
我也发现了同样的问题，同问 @jasondu 是不是应该配置一下什么参数？感谢！

**Comment by steveny-l** [comment]
> 我也发现了同样的问题，同问 @jasondu 是不是应该配置一下什么参数？感谢！

把组件absolute一下～然后放到页面外

**Comment by ifuweimin** [comment]
@steveny-l  谢谢，可以了
