### ISSUE TITLE
blocks中的圆角，borderRadius二分之一处理，感觉不用除以2 

### ISSUE THREAD

**Issue by FourNoMan** [jasondu/wxa-plugin-canvas#33]
比如，宽高都为200，borderRadius为100，此时应该为一个圆形，但是插件中处理后画出来的不是圆形，去掉二分之一处理后，画出来的就为正常的圆形了。

**Comment by jasondu** [comment]
之前是按照直径来的

**Comment by FourNoMan** [comment]
哦哦，我是直接使用的css生成的数据结构，所以感觉和原页面效果不一样

> 之前是按照直径来的

weizaidu

**Comment by FourNoMan** [comment]
> 之前是按照直径来的

哦哦，我是直接使用css生成的数据结构，所以看着和原页面效果不一样

**Comment by jasondu** [comment]
只能你做个转换，或者改一下组件源码了
