### ISSUE TITLE
在wepy上怎么使用呢

### ISSUE THREAD

**Issue by 1104792149** [jasondu/wxa-plugin-canvas#40]

**Comment by jasondu** [comment]
目前不支持wepy

**Comment by AJLoveChina** [comment]
其实作者的意思大家可能会误解
不支持wepy 指的是不支持 npm 依赖方式的开发
你仍然可以把作者的代码直接下载到  wepy 项目中使用 下面是我写的一个的例子(已测试可以完美运行 无坑给作者点赞 逃~~)

https://github.com/AJLoveChina/wechat-qipaceyan/blob/4f965d707eaca5c67111afb402810a07207872d8/src/pages/result.wpy#L281

**Comment by FannyFanFan** [comment]
@AJLoveChina getImageInfo:fail file not found 有这样的报错。。能加一下你微信吗

**Comment by AJLoveChina** [comment]
@FannyFanFan 我在使用过程中使用本地图片偶尔会出现这样的情况,  后面换成网络图片就好了
我的Q: 735267452
