### ISSUE TITLE
有没有demo示范

### ISSUE THREAD

**Issue by CarryOnHxy** [jasondu/wxa-plugin-canvas#52]
有demo感觉用起来快一点，不过花canvas部分有点麻烦

**Comment by 1c7** [comment]
这个库里的 index 就是 demo
![image](https://user-images.githubusercontent.com/1804755/50444055-32201b80-0941-11e9-8c87-6296f950e2f5.png)
可以把整个库 git clone 下来用开发者工具打开就看得到了

**Comment by jasondu** [comment]
感谢帮忙回复
