### ISSUE TITLE
_downImage第二次制作不被调用

### ISSUE THREAD

**Issue by sunzhongshi** [jasondu/wxa-plugin-canvas#55]
您好：
       我最近再做一个可编辑海报的功能，用到了您写的插件，但是晕倒了一个问题！就是每次第一次制作海报的时候可以正确的执行。但是我在第二次调用本地相册选择图片然后在制作海报的时候！制作成功后还是我第一次制作的图片！URL路径已经换成功了！经过我的调试发现在第二次制作海报的时候插件index.js里面的_downImage方法不回调用。_downImage只在第一次制作的时候会调用之后不会再调用。这个问题困扰了我很久，请您帮忙解答！

**Comment by huwenjian** [comment]
您好，poster/index.js 中有downloadResource()方法  会判断图片是否下载完毕 
1. 你可以改成如下
downloadResource() {
            return new Promise((resolve, reject) => {
                const poster = this.selectComponent('#poster');
                // if (this.downloadStatus && this.downloadStatus !== 'fail') {
                if (0) { // <==============将其改为每次都执行差不多就这个意思

                    if (this.downloadStatus === 'success') {
                        resolve();
                    } else {
                        this.once('downloadSuccess', () => resolve());
                        this.once('downloadFail', (e) => reject(e));
                    }
                } else {
                    poster.downloadResource(this.data.config.images)
                        .then(() => {
                            this.downloadStatus = 'success';
                            resolve();
                        })
                        .catch((e) => reject(e));
                }  
            })
        },
2. 或者 自己变换的时候将downloadSuccess 改变

希望可以帮到你
O(∩_∩)O哈哈~

**Comment by lianwenliang** [comment]
https://github.com/jasondu/wxa-plugin-canvas/issues/43
应该跟我遇到的问题是一样的

**Comment by jasondu** [comment]
https://github.com/jasondu/wxa-plugin-canvas/pull/72 已经修复
