### ISSUE TITLE
给本地的图片地址无效：downloadFile:fail invalid url

### ISSUE THREAD

**Issue by AsherSun** [jasondu/wxa-plugin-canvas#6]
`{
        width: 470,
        height: 836,
        zIndex: 1,
        x: 0,
        y: 0,
        url: '/images/shopShareBG.png'
      }`

**Comment by AsherSun** [comment]
必须要网络地址吗？

**Comment by jasondu** [comment]
是的，目前不支持本地图片，我今天补上把，但不建议用本地，因为本地图片会让小程序包增大

**Comment by jasondu** [comment]
已经改好，版本1.1.4
