### ISSUE TITLE
网络资源图片下载的耗时问题

### ISSUE THREAD

**Issue by AsherSun** [jasondu/wxa-plugin-canvas#7]
a、插件绘制的过程中，如果有相关网络资源图。会进行下载... 在这个流程中存在图片下载耗时的问题，对用户体验有点不友好。

b、能否提供一个函数，可以让使用者在页面onLoad函数中调用进行图片预下载。这样可以减少在绘制过程需要先下载网络资源图。

**Comment by jasondu** [comment]
好主意，我想想方案，今天优化一下

**Comment by jasondu** [comment]
https://github.com/jasondu/wxa-plugin-canvas/tree/dev  dev分支新增了预加载功能和隐藏loading功能，可以试用

**Comment by jasondu** [comment]
已经在1.1.5版本解决
