### ISSUE TITLE
图片的borderRadius有时候会失效

### ISSUE THREAD

**Issue by chestnutttt** [jasondu/wxa-plugin-canvas#71]
就在看官方提供的demo的时候，将小程序二维码图代码删除后，顶部头像的圆角效果会消失。然后给其他图片添加borderRadius属性无效果；把案例图片替换掉也会失效。

**Comment by jasondu** [comment]
是真机还是开发工具

**Comment by jasondu** [comment]
开发工具有时会抽风，真机没事就好了

**Comment by capadong** [comment]
> 开发工具有时会抽风，真机没事就好了

多谢回复。
还有一个问题请教一下，文字可以加粗吗？

**Comment by jasondu** [comment]
@capadong 在V1.1.10已经支持加粗
