### ISSUE TITLE
生成海报以后，关掉preview页面，原页面还有海报

### ISSUE THREAD

**Issue by congyingww** [jasondu/wxa-plugin-canvas#79]

**Comment by jasondu** [comment]
index.wxss文件中的.canvas.pro样式transform: translate3d(-999rpx, 0, 0);数值改成-9999rpx试试

**Comment by congyingww** [comment]
把 debug: false 就好了  ；debug: true的时候 ，数值改成-9999rpx也没用

**Comment by jasondu** [comment]
是的，debug需要设置成false
