### ISSUE TITLE
请问怎么使用本地图片啊？

### ISSUE THREAD

**Issue by szhst6163** [jasondu/wxa-plugin-canvas#8]
我使用本地路径的话会报错 downloadFile:fail Error: getaddrinfo ENOTFOUND tmp tmp:443

**Comment by jasondu** [comment]
查看是不是使用最新版本1.1.4，地址传入相对地址或者绝对地址都可以

**Comment by szhst6163** [comment]
果然是我的版本不是最新的。。谢谢你 解决了
