### ISSUE TITLE
生成海报的图片可以不是链接地址吗？

### ISSUE THREAD

**Issue by gaohongwei0501** [jasondu/wxa-plugin-canvas#81]
我们的生成的海报要加上小程序码，这个小程序码是微信接口生成的，会带有动态参数，我们的后台项目不想存这个图片，想把图片的base64编码返给我，这样海报组件用不了。或者有其他的方案吗？

**Comment by jasondu** [comment]
之前我尝试过通过base64生成海报，是不支持的
