### ISSUE TITLE
图片地址支持云文件吗？

### ISSUE THREAD

**Issue by hxdaxu** [jasondu/wxa-plugin-canvas#85]
图片地址支持云文件吗？

**Comment by jasondu** [comment]
你可以把云文件地址填进去试试看，如果不行我加一下

**Comment by hxdaxu** [comment]
不可以。现在我是将云文件转换为临时链接，然后再生成的。
希望支持一下。

**Comment by jasondu** [comment]
我看了一下的确需要将云文件转换为临时链接，这个转换的过程不应该放在组件里面，还是由你们自己写比较好
