### ISSUE TITLE
文字自动换行后能否返回实际所用行数？

### ISSUE THREAD

**Issue by aetherwu** [jasondu/wxa-plugin-canvas#90]
听上去有点zuo，不过还是想问一下，因为这样可以更方便地实现图片尺寸在长度上的自适应（捂脸

**Comment by jasondu** [comment]
长度可以不用设置的，不设置为自适应哦

**Comment by aetherwu** [comment]
emmm.... 好像还是需要自己计算好（因为有的时候想自适应行数，并且保持留白适应，这样需要预先计算整体高度变化什么的）
