### ISSUE TITLE
老大这个是怎么做的呢？

### ISSUE THREAD

**Issue by famhoo** [jasondu/wxa-plugin-canvas#98]
![删01](https://user-images.githubusercontent.com/39912339/54761179-94c94080-4c2c-11e9-9077-c4b08453fb63.jpg)
这个海报是用我们这个组件做的，请问老大这是怎么做的呢？是做进模板吗还是用个什么蒙板？这个蒙板怎么做？还有，除了保持长按的功能外，下面另加了“保存到相册分享”的提示。我们这个海报组件能不能升级成这个样子，让海报缩小浮在文章上面有所区分

**Comment by jasondu** [comment]
可以的，成功回调只是生成一张图片地址，你可以自己做个像上面一样的弹框，然后把图片放在里面展示就行了，自己再做一个“保存到相册分享”的按钮，点击的时候把图片保存在本地就行了

**Comment by cnstampbird** [comment]
> 可以的，成功回调只是生成一张图片地址，你可以自己做个像上面一样的弹框，然后把图片放在里面展示就行了，自己再做一个“保存到相册分享”的按钮，点击的时候把图片保存在本地就行了

生成图片后临时文件路径 detail 在模拟器上以http://tmp开头，在直机上以wxfile://开头，两种协议均不支持置入标签<img />，我加入后均无法正常显示生成后的图片，一直加载中，请问一下有什么办法解决？不想将图片上传到指定服务后返回链接，这样做的话开支开太了。

**Comment by famhoo** [comment]
@jasondu 大神你把这功能做进下一个版本的DEMO里吧，期待哦。。。

**Comment by jasondu** [comment]
@famhoo @cnstampbird 我一会写个DEMO

**Comment by famhoo** [comment]
@jasondu 拥护大神，小程序海报就咱们一家强！！万分期待。。。
